"""Prepare auditable slide evidence from frozen local study artifacts."""
from analyze import *
from analyze_figure_revision import case_values
OUT=ROOT/'findings/medcase24-slides'

def main():
 (OUT/'build').mkdir(exist_ok=True,parents=True)
 D=json.loads((DEST/'summary.json').read_text());F=json.loads((ROOT/'findings/medcase24-figures/figure-data.json').read_text());M=json.loads((ROOT/'findings/medcase24-merging/analysis.json').read_text())
 cases=[json.loads(l) for l in (ROOT/'data/medcasereasoning/pilot24/cases.jsonl').read_text().splitlines()];case=next(c for c in cases if 'PMC3420544' in c['id']);runs=load_runs();run=next(r for r in runs if r['case']==case['id'] and r['condition']=='split-specialist')
 roles={x['case']+'|'+x['condition']:x['role_by_seat'] for x in D['role_mapping']};edges=json.loads((DEST/'social-uptake-observations.json').read_text())['edges'];flow=[]
 for a,b in itertools.product(FIELDS,repeat=2):
  es=[e for e in edges if e['unit']=='equivalence' and e['scope']=='all' and e['match']=='equivalence' and roles[e['case']+'|'+e['condition']][e['seat']]==a and roles[e['case']+'|'+e['condition']][e['target']]==b]
  cv=case_values(es);flow.append({'source':a,'target':b,'rate':avg(cv.values()),'cases':len(cv)})
 viewer=[]
 for cid,ids in [('B|1',[1295]),('A|2',[380]),('C|2',[1082])]:
  c=next(c for c in run['cards'] if c['id']==cid);f=next(f for f in c['facts'] if f['id']==ids[0]);viewer.append({'card':cid,'fact':f,'text':run['atoms'][str(f['id'])][0],'output':c['text']})
 links=[]
 for target,node in [('A|2',380),('C|2',1082)]:
  score=next(x for x in run['scores'] if set(x[:2])=={1295,node});assert min(score[2:])>=5.28;assert 'B|1' in next(c for c in run['cards'] if c['id']==target)['visible'];links.append({'source':'B|1','target':target,'scores':score})
 result={'case':case,'agents':run['agents'],'viewer':viewer,'viewer_links':links,'flow':flow,'accuracy':D['accuracy'],'figures':{k:v for k,v in F.items() if k in ['01_uptake_prime','output_own','novel-interaction-output_own','factorial-pooled-peers','correctness-pooled-boxplot','majority-pooled-boxplot','pooled-inference'] or k.startswith('token-R')},'merging':M}
 (OUT/'build/evidence.json').write_text(json.dumps(result,separators=(',',':')))
 # Report exact ratios and paired contrasts. All comparisons exploratory in this selected pilot.
 lines=['# Cross-round merging in the MedCase24 pilot','', 'All calculations are offline. The five conditions share the same 24 selected cases. Effects below are paired within case. They describe the saved fact labels, not clinical truth.','', '## Two complementary measures','', '**Cross-round compression C = 1 − N(all rounds) / [N(R1) + N(R2) + N(R3)].** Each N counts output-only equivalence components. A higher C means that pooling rounds removes a larger fraction of the separately counted units. This is a normalized merging level, not a per-edge probability.','', '**Direct recurrence D.** For each round pair, find units with an identity or direct equivalence link to at least one unit in the other round. Average the matched fraction from both sides, then average R1/R2, R1/R3 and R2/R3. D uses within-round units but no cross-round closure. A raw-atom version uses no union-find at all.','', '| Setting | Compression C | Direct recurrence D | Raw atom recurrence |','|---|---:|---:|---:|']
 for c in M['conditions']:lines.append('| '+c['condition']+' | '+' | '.join(f"{100*c[k]['mean']:.1f}%" for k in ['compression','direct_coverage','raw_direct_coverage'])+' |')
 lines += ['', '## Shared minus split, paired by case','', '| Role configuration | Metric | Difference, pp | 95% case-bootstrap CI, pp |','|---|---|---:|---:|']
 for x in M['contrasts']:
  if x['left'].startswith('shared') and x['right'].startswith('split') and x['metric'] in ['compression','direct_coverage','raw_direct_coverage']:lines.append(f"| {x['left'].split('-')[1]} | {x['metric']} | {100*x['mean']:+.1f} | [{100*x['lo']:+.1f}, {100*x['hi']:+.1f}] |")
 lines += ['', 'All six exploratory contrasts have two-sided case sign-flip p < .001 and BH q < .001 (100,000 draws). The uncertainty unit is 24 cases, not 120 traces or thousands of edges.','', '## What accounts for the compression difference?','', 'Compression decomposes exactly into (1) repeated global-cluster round presences and (2) additional merging of within-round components through cross-round bridges. These are accounting terms under the final equivalence partition, not independent causal mechanisms.','', '| Setting | Repeated-presence share | Bridge share |','|---|---:|---:|']
 for c in M['conditions']:lines.append(f"| {c['condition']} | {100*c['repeat_share']['mean']:.1f}% | {100*c['bridge_share']['mean']:.1f}% |")
 lines += ['', 'Shared–split compression differences split almost equally between the two terms for generic agents (6.9 pp repeated presence, 6.5 pp bridges). For specialists they are 4.6 pp and 7.2 pp. Raw atom recurrence is also 17–20 pp higher under shared information, so a union-find artifact alone cannot account for the pattern.','', '## Persistence across rounds and thresholds','', 'Direct recurrence grows from R1/R2 to R2/R3 in every setting. Shared generic rises from 53.9% to 66.5%, while split generic rises from 33.1% to 53.1%. Shared specialist rises from 54.5% to 64.7%, versus 36.1% to 54.2% for split specialist. Communication narrows the descriptive gap, but it remains at the final transition.','', 'Across saved-margin thresholds 4.5, 5.0, 5.28, 5.5 and 6.0, the shared–split compression gap stays about 11.6–13.8 pp. The direct-recurrence gap stays about 14.7–18.2 pp. Blocker-negative pairs stay unrelated throughout. Threshold sensitivity does not establish the accuracy of the matching model.','', '## Interpretation','', 'In this controlled pilot, information allocation changes cross-round redundancy much more than role labels change it. Within shared information, specialist−generic compression is +0.3 pp [−2.2, +2.7]. Within split information it is +1.9 pp [−0.6, +4.2]. Mismatch−matched-specialist compression is +1.7 pp [−0.5, +3.9]. These smaller contrasts do not establish a role-driven compression difference.','', 'A supported description is: splitting initial evidence leaves more distinct content across rounds and less direct recurrence, even after normalization. A plausible mechanism is that agents start with different evidence and revise their content after receiving peers, whereas shared agents can repeatedly select the same evidence. This mechanism remains a hypothesis: C and D do not distinguish repeated evidence, independent derivation and actual copying, and the pilot has one trace per case-condition.','', 'Use C as a single trace-level merging feature and D as its direct-match robustness companion. Lower merging is neither necessarily better nor necessarily worse: retained diversity can reflect useful complementarity, unresolved disagreement, or unsupported content. Final diagnosis labels do not supply gold truth for every atomic fact.','', 'Reproduce: `.venv/bin/python scripts/study_report/merge_levels.py`. Full case-level values, paired differences, round pairs and threshold sensitivity are in `analysis.json`.']
 (ROOT/'findings/medcase24-merging/README.md').write_text('\n'.join(lines)+'\n')
 (ROOT/'docs/medcase24-merging.md').write_text('\n'.join(lines)+'\n')
 print('Prepared slide evidence and merging report')
if __name__=='__main__':main()
